name: Generate Snake Contribution Grid  
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation  
        uses: Platane/snk@v3  
        with:
          github_user_name: harshdwivediiiii
          outputs: dist/snake.svg

      - name: Upload the Snake Animation  
        uses: actions/upload-artifact@v3  
        with:
          name: snake-animation
          path: dist/snake.svg
